project_name: sync-dotenv

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64

brew:
  github:
    owner: atrox
    name: homebrew-tap
  commit_author:
    name: atrox
    email: hello@atrox.dev
  homepage: 'https://github.com/atrox/sync-dotenv'
  description: 'sync-dotenv helps you to keep your .env.example in sync with your .env file.'
  test: |
    system "#{bin}/sync-dotenv --version"

scoop:
  bucket:
    owner: atrox
    name: scoop-bucket
  commit_author:
    name: atrox
    email: hello@atrox.dev
  homepage: 'https://github.com/atrox/sync-dotenv'
  description: 'sync-dotenv helps you to keep your .env.example in sync with your .env file.'
  license: MIT

nfpms:
- homepage: 'https://github.com/atrox/sync-dotenv'
  description: 'sync-dotenv helps you to keep your .env.example in sync with your .env file.'
  license: MIT
  maintainer: 'Atrox <hello@atrox.dev>'
  vendor: 'atrox.dev'
  formats:
    - deb
    - rpm

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
