name: release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  tests:
    name: run tests and build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run tests
        uses: docker://golang:latest
        with:
          entrypoint: go
          args: test -race -coverprofile=coverage.txt -covermode=atomic

      - name: send coverage to codecov
        uses: Atrox/codecov-action@v0.1.3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: goreleaser
        uses: docker://goreleaser/goreleaser
        env:
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release
